services:
  - type: web
    name: folioscraper-V2
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: python app.py
    autoDeploy: true
