services:
  - type: web
    name: folioscraper-V2
    env: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    autoDeploy: true
    plan: starter
    envVars:
      - key: PORT
        value: "8080"
