services:
  - type: web
    name: folioscraper-V2
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: playwright install && gunicorn app:app -b 0.0.0.0:$PORT
    autoDeploy: true
